/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package semana_02_03;

/**
 *
 * @author PC
 */
public class FormCambioSDE extends javax.swing.JFrame {

    /**
     * Creates new form FormCambioSDE
     */
    
    // private Class_CambioForm cambio; // Llamando la otra clase
    
    public FormCambioSDE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblPrecioDolares = new javax.swing.JLabel();
        lblPrecioSoles = new javax.swing.JLabel();
        lblPrecioEuros = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtPrecioDolares = new javax.swing.JTextField();
        txtPrecioSoles = new javax.swing.JTextField();
        txtPrecioEuros = new javax.swing.JTextField();
        btnDisminuirPrecio = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCodigo.setText("Codigo");

        lblMarca.setText("Marca");

        lblColor.setText("Color");

        lblPrecioDolares.setText("PrecioDolares");

        lblPrecioSoles.setText("PrecioSoles");

        lblPrecioEuros.setText("PrecioEuros");

        btnDisminuirPrecio.setText("Disminuir");
        btnDisminuirPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirPrecioActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrecioDolares)
                            .addComponent(lblColor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMarca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioSoles, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioEuros, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPrecioSoles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txtPrecioDolares, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtColor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioEuros)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProcesar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDisminuirPrecio)
                        .addGap(11, 11, 11)
                        .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioDolares)
                    .addComponent(txtPrecioDolares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioSoles)
                    .addComponent(txtPrecioSoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioEuros)
                    .addComponent(txtPrecioEuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisminuirPrecio)
                    .addComponent(btnVolver)
                    .addComponent(btnProcesar))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisminuirPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirPrecioActionPerformed
        // TODO add your handling code here:
        Class_CambioForm Cambio_obj = new Class_CambioForm(1234, "HP", "Negro", 500.0);
    
        // Disminuir el precio en dólares en un 10%
        Cambio_obj.disminuirPrecioDolares(10.0);
    
        // Mostrar la información actualizada en las cajas de texto
        txtCodigo.setText(Integer.toString(Cambio_obj.getCodigo()));
        txtMarca.setText(Cambio_obj.getMarca());
        txtColor.setText(Cambio_obj.getColor());
        txtPrecioDolares.setText(Double.toString(Cambio_obj.getPrecioDolares()));
        txtPrecioSoles.setText(Double.toString(Cambio_obj.getPrecioSoles()));
        txtPrecioEuros.setText(Double.toString(Cambio_obj.getPrecioEuros()));
    }//GEN-LAST:event_btnDisminuirPrecioActionPerformed

    
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        
        Class_CambioForm Cambio_obj = new Class_CambioForm(1234, "HP", "Negro", 500.0);

        // Mostrar la información completa en las cajas de texto
        txtCodigo.setText(Integer.toString(Cambio_obj.getCodigo()));
        txtMarca.setText(Cambio_obj.getMarca());
        txtColor.setText(Cambio_obj.getColor());
        txtPrecioDolares.setText(Double.toString(Cambio_obj.getPrecioDolares()));
        txtPrecioSoles.setText(Double.toString(Cambio_obj.getPrecioSoles()));
        txtPrecioEuros.setText(Double.toString(Cambio_obj.getPrecioEuros()));
    }//GEN-LAST:event_btnVolverActionPerformed

    
    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
        Class_CambioForm Cambio_obj = new Class_CambioForm(1234, "HP", "Negro", 500.0);
        // Mostrar la información completa en las cajas de texto
        txtCodigo.setText(Integer.toString(Cambio_obj.getCodigo()));
        txtMarca.setText(Cambio_obj.getMarca());
        txtColor.setText(Cambio_obj.getColor());
        txtPrecioDolares.setText(Double.toString(Cambio_obj.getPrecioDolares()));
        txtPrecioSoles.setText(Double.toString(Cambio_obj.getPrecioSoles()));
        txtPrecioEuros.setText(Double.toString(Cambio_obj.getPrecioEuros()));
    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCambioSDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCambioSDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCambioSDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCambioSDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCambioSDE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisminuirPrecio;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPrecioDolares;
    private javax.swing.JLabel lblPrecioEuros;
    private javax.swing.JLabel lblPrecioSoles;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPrecioDolares;
    private javax.swing.JTextField txtPrecioEuros;
    private javax.swing.JTextField txtPrecioSoles;
    // End of variables declaration//GEN-END:variables
}
